version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    env_file:
      - .env-non-dev
  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    ports:
      - 9999:8000
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 9998:8080