"""empty message

Revision ID: a94f9bd6b816
Revises: 1900a46e5db9
Create Date: 2024-03-11 12:04:46.127470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94f9bd6b816'
down_revision: Union[str, None] = '1900a46e5db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE transactionstatus ADD VALUE 'was_predict'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
